# Generated by Django 5.2.15 on 2026-06-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Doctor', 'Doctor'), ('Patient', 'Patient')], default='Patient', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tel_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
